### ISSUE TITLE
When I use the TG80211Family. Kext driver, sleep startup fails

### ISSUE THREAD

**Issue by YahuiWong** [vulgo/ga-h97n-wifi-hackintosh#10]
remove  TG80211Family. Kext  ,sleep startup work

**Comment by vulgo** [comment]
Is there a panic report you can attach. Or output from

```
pmset -g log
```

**Comment by YahuiWong** [comment]
it`s still not working,what is network card of you use?

**Comment by vulgo** [comment]
I have used BCM94360NG in the past. For this board you will want an adapter.

[BCM94360NG m.2](https://www.aliexpress.com/wholesale?SearchText=BCM94360NG)
[m.2 mini PCIe adapter](https://www.aliexpress.com/wholesale?SearchText=m.2+ngff+mini+pci+wifi+adapter)

**Comment by vulgo** [comment]
One other thing. The Broadcom driver does read a registry property that was missing until commit 6d1d4d33bec3d2fa812a39872b7c1df55d897497. You might make that change and see if it resolves the wake issue with `TG80211Family.kext`

`config.plist` -> `ACPI` -> `Add`

Change `SSDT-SLPT.aml` -> `SSDT-SLTP.aml`

**Comment by vulgo** [comment]
Closing as wireless hardware is out of scope.
