### ISSUE TITLE
how to disable -v?

### ISSUE THREAD

**Issue by YahuiWong** [vulgo/ga-h97n-wifi-hackintosh#2]
Every time it starts, there is a -v message. How to remove this?

**Comment by vulgo** [comment]
Yes we should have persistent boot arguments.

[https://github.com/vulgo/ga-h97n-wifi-hackintosh/commit/26b48f779405d95532109f877270d0da4d5d105f](https://github.com/vulgo/ga-h97n-wifi-hackintosh/commit/26b48f779405d95532109f877270d0da4d5d105f)

Then we can just do

```
nvram boot-args=""
```

and also SIP

```
csrutil enable | disable
```
