### ISSUE TITLE
bluetooth no working with DW1550 on Monterey

### ISSUE THREAD

**Issue by hatran0884** [vulgo/ga-h97n-wifi-hackintosh#21]
Hi 
thank you for your work, with your EFI, I have made almost perfect hackintosh. so far, I only have an issue with the bluetooth using DW1550 mini PCIE on Monterey. I have still been struggling to make it work
I have used the kexts from acidanthera/BrcmPatchRAM and followed exactly what are mentioned but no solution works. 
so I am reaching you here to see if you have a solution or workaround ? or have any experience with this case? 
Wifi works just fine using AirportBrcmFixup
for your info, I have a H97N-Wifi with Samsung 256GB SSD, 16GB RAM and HD4600 iGPU and I use iMAC 18,1 as suggested by your guide.

**Comment by vulgo** [comment]
Unless I misunderstand I don't find the wifi PCI device or bluetooth product IDs from [here](https://deviwiki.com/wiki/Dell_Wireless_1550_(DW1550)) anywhere in /System/Library/Extensions/*

Without one of a

- third-party driver
- 'forward-ported' driver
- device ID spoofing
- Lilu patching solution

this card likely will not work in Monterey. Even with the above it may not work correctly.

Either

- find someone who got it to work and do as they did
- get compatible hardware

I don't use wifi that much. I'm hoping to have ethernet on my phone soon.

**Comment by hatran0884** [comment]
actually broadcom DW1550 card is pretty common as a native supported wifi solution in MAC, I bought this card because of it, but it actually only works well with the previous MAC OS version and currently it hasnt been able to work reliably with Monterey. I am still trying to find a solution for it.

**Comment by hatran0884** [comment]
by the way, do you know how to use the Power Button to get the OS to go sleep ?

**Comment by vulgo** [comment]
> actually broadcom DW1550 card is pretty common as a native supported wifi solution in MAC, I bought this card because of it, but it actually only works well with the previous MAC OS version


#### Supported *chipsets* on macOS 12

- BCM43602
- BCM4350
- BCM4360

Apple's own cards with an adapter are best. Some 3rd party m.2 cards claim native support and require a mini-PCIe adapter. Some require fix-up. Some don't work properly.

> do you know how to use the Power Button to get the OS to go sleep ?

#### Show the shutdown dialog

Control + Power Button

#### Sleep

Control + Shift + Power button

#### Shutdown 

Control + Option + Command + Power button

**Comment by vulgo** [comment]
I think i bought the same chipset a few years ago when it worked in macOS. Still works in Linux.

I've a BCM4360NG in a desktop Monterey system, however i find a simple cable is much neater than the external antennas on a desktop of our general type.

Search acidanthera bugtracker for up to date information re 4360 i heard some were having issues

**Comment by hatran0884** [comment]
I guess your usbmap tool modified specially to the mobo H97N-Wifi actually is not 100% working in my case, so the tool probably miss some internal port used for bluetooth controller. the type for the bluetooth controller should be 255. 
so do you think I should use this tool below to re-edit my ports for bluetooth controller: 
https://github.com/corpnewt/USBMap

**Comment by vulgo** [comment]
Added `BrcmPatchRam` link to `out-of-scope` section of `README.md`

**Comment by vulgo** [comment]
Unless you have 2 USB 2.0 ports plugged into boxless motherboard header `HS05` and `HS06` should be turned off in the tool.

`HS11` is on the mini PCIe socket so no thumb drive will connect to it, usually only bluetooth.

Make sure you replace the kext in OpenCore `Kexts` folder with the one from the new desktop.
