### ISSUE TITLE
Did you use nvme m2 ssd?

### ISSUE THREAD

**Issue by YahuiWong** [vulgo/ga-h97n-wifi-hackintosh#24]
I want to use pcie to convert nvme's adapter, but can't confirm if macos12 is applicable

**Comment by YahuiWong** [comment]
Are you use the pcie?

**Comment by vulgo** [comment]
Yes, I have such a setup using the iGPU for graphics and the PCIe for storage. If you have an electrically sound PCIe to m.2 board the firmware has complete support for NVMe devices, refer to the H97N-WIFI manual. Also take a look at NVMeFix.kext and Dortania's NVMe documentation for known problems and fixes in macOS.

**Comment by YahuiWong** [comment]
> Yes, I have such a setup using the iGPU for graphics and the PCIe for storage. If you have an electrically sound PCIe to m.2 board the firmware has complete support for NVMe devices, refer to the H97N-WIFI manual. Also take a look at NVMeFix.kext and Dortania's NVMe documentation for known problems and fixes in macOS.

Can you recommend your conversion card model?

**Comment by vulgo** [comment]
I can't find the order, mine is a riser card, has no bracket and is held in place by the PCIe slot release lever and a foam bumper attached to side of the system enclosure for horizontal stability (in other words so it does not wobble).

If you have a PCI slot on a larger enclosure you might want the common PCIe card type with a bracket and screw.

Any card without manufacturing defects would work.
