### ISSUE TITLE
Sorry to contact you this way

### ISSUE THREAD

**Issue by 1alessandro1** [vulgo/ga-h97n-wifi-hackintosh#3]
There was another guy in the past who had your exact username, he hosted NoVpaJpeg and an old version of ioregistryexplorer. 

Could you please create a public repository hosting the source code (i made a master backup here)

[IORegistryExplorer-master.zip](https://github.com/vulgo/ga-h97n-wifi-hackintosh/files/5880667/IORegistryExplorer-master.zip)

the url should be:

https://github.com/vulgo/IORegistryExplorer

Thanks in advance for your patience

**Comment by vulgo** [comment]
It's been done, the link is working.
