### ISSUE TITLE
Error while building cache

### ISSUE THREAD

**Issue by mygithub2021007** [vulgo/ga-h97n-wifi-hackintosh#31]
Getting followingg error:

 Unable to build new kernel cache
Subprocess failed.
    Command: ['/Library/PrivilegedHelperTools/com.dortania.opencore-legacy-patcher.privileged-helper', '/usr/bin/kmutil', 'create', '--new', 'aux', '--boot-path', '/System/Volumes/Update/mnt1/System/Library/KernelCollections/BootKernelExtensions.kc', '--system-path', '/System/Volumes/Update/mnt1/System/Library/KernelCollections/SystemKernelExtensions.kc', '--allow-missing-kdk']
    Return Code: 71
    Standard Output:
        No variant specified, falling back to release
        No variant specified, falling back to release
        Error Domain=KMErrorDomain Code=71 "Unable to resolve dependencies: 'com.wdc.driver.USB-64HP' names a dependency on 'com.apple.iokit.IOUSBMassStorageClass', which was not found." UserInfo={NSLocalizedDescription=Unable to resolve dependencies: 'com.wdc.driver.USB-64HP' names a dependency on 'com.apple.iokit.IOUSBMassStorageClass', which was not found.}
    Standard Error:
        None

**Comment by vulgo** [comment]
Hi. You will have to contact the authors of the com.wdc.driver.USB-64HP driver, remove it from the build if it is causing it to fail. You may not need it
