### ISSUE TITLE
WiFi and Ethernet

### ISSUE THREAD

**Issue by ainsleyrutterford** [vulgo/ga-h97n-wifi-hackintosh#4]
Really nice repo, planning on installing macOS Big Sur on a GA-h97N-WIFI next week and was looking around to see if it's been done before and was pleasantly surprised to find such a recently updated repo!

I just had a couple questions about WiFi/Bluetooth and Ethernet. Do you have any working WiFi at the moment? I believe the card is Intel so it won't work out of the box? Have you used a USB dongle or perhaps swapped the card out for something else? I think the BCM94360NG should fit and work fine, do you think so too?

Also, I was just wondering why you have `AtherosE2200Ethernet.kext`, `IntelMausiEthernet.kext`, and  `RealtekRTL8111.kext`? Shouldn't we only need one Ethernet kext?

Thanks :)

**Comment by vulgo** [comment]
I haven't used wifi on this board. BCM94360NG is compatible, it should work OOB. An m.2 card will need an adapter for the mini PCI express slot on H97N-WIFI.

As for ethernet, you only need one kext. There are two versions of this board with either Realtek or Atheros, both have Intel ethernet as well. You can disable in firmware settings the controller you aren't using and remove the unnecessary kexts from your EFI partition.

**Comment by ainsleyrutterford** [comment]
Okay great, thanks!
